### ISSUE TITLE
Possible recursion detected

### ISSUE THREAD

**Issue by inethui** [AqlaSolutions/AqlaSerializer#37]
I got the error message when I tried to deep clone an object twice:
`Possible recursion detected (offset: 8 level(s)): []`

The first deep clone was successful, I checked the object's fields and everything seems to be ok. However, if I deep clone the same object again, I got an exception with the above error message.

The recursion stack dump is like this:
```
Stack:
[]
[]
[]
[]
[]
[]
[]
[]
[]
```
What does this error mean and how can I trouble-shoot it?

Thanks

**Comment by inethui** [comment]
The exception call stack is like this:
```
   at AqlaSerializer.ProtoWriter.CheckRecursionStackAndPush(Object instance)
   at AqlaSerializer.ProtoWriter.StartSubItem(Object instance, ProtoWriter writer, Boolean allowFixed)
   at AqlaSerializer.ProtoWriter.StartSubItem(Object instance, Boolean prefixLength, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at AqlaSerializer.Serializers.CompiledSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
   at AqlaSerializer.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest, Boolean isRoot)
   at AqlaSerializer.Meta.TypeModel.DeepClone(Object value)
   at AqlaSerializer.Meta.TypeModel.DeepClone[T](T genericValue)
   at AqlaSerializer.Serializer.DeepClone[T](T instance)
```

**Comment by AqlaSolutions** [comment]
Please turn off AutoCompile before posting stack traces

**Comment by inethui** [comment]
This is the stack trace without AutoCompile:
```
AqlaSerializer.ProtoWriter.CheckRecursionStackAndPush
AqlaSerializer.ProtoWriter.StartSubItem
AqlaSerializer.ProtoWriter.StartSubItem
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NoNullDecorator.Write
AqlaSerializer.Serializers.FieldDecorator.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.TypeSerializer.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.ProtoWriter.WriteRecursionSafeObject
AqlaSerializer.Serializers.ModelTypeSerializer.AqlaSerializer.Serializers.IProtoSerializer.Write
AqlaSerializer.Serializers.NetObjectValueDecorator.Write
AqlaSerializer.Serializers.RootDecorator.Write
AqlaSerializer.Meta.RuntimeTypeModel.Serialize
AqlaSerializer.Meta.TypeModel.DeepClone

```

**Comment by AqlaSolutions** [comment]
Please read this: https://github.com/AqlaSolutions/AqlaSerializer/wiki/Member-Formats#latereference-mode

**Comment by AqlaSolutions** [comment]
Also the `[] ` in the exception is `ToString()` of your object at the top of the serialization stack

**Comment by AqlaSolutions** [comment]
It's possible that you are trying to serialize a reference without reference tracking but it contains reference to itself inside

**Comment by inethui** [comment]
I tried "LateReference" but it didn't work. I'm frustrated that it works for the first clone but failed for the second clone. What could probably cause this kind of behavior? The code has been in production for more than 10 years successfully. Also with BinaryFormatter we don't have any issue.

**Comment by AqlaSolutions** [comment]
Then I would just use a debugger with a breakpoint at `CheckRecursionStackAndPush` to check what's going on.

**Comment by inethui** [comment]
I have found out the cause of this. Basically our code mistakenly treats IEnumerable types as ValueFormat.Compact.
